### ISSUE TITLE
Add support for dialects

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#174]

**Comment by thadguidry** [comment]
MUST add a user story here.  Dialects might mean keeping backwards compatibility at an API query level (something that dialects happen to do in the SQL world actually).  We should present in a user story a problem sentence or two.  Correctly define the problem(s) and then write up the user story on this because... dialects can have huge disparity even WITHIN a single ecosystem, say like PostgreSQL ... because DB Extensions can expand and in rare cases, sometimes replace functionality that becomes non-backwards compatible, depending on the extension installed.  So saying "support dialects" is a very naive way of saying "support the entire universe of db vendors and extensions and all forms of UDF's, while we're at it."  This is not about just saying "we understand PL/pgSQL and T-SQL".

Write up a proper problem or two into user stories.

**Comment by kdhrubo** [comment]
Yes, so far these differences have been handled very efficiently in a generic way. So no need to jump in and implement dialects - it is not really a pressing requirement at present.
