### ISSUE TITLE
Make h2 default database to simplify installation

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#234]

**Comment by thadguidry** [comment]
Wait, what was the idea here about having h2 a default db to simplify install of db2rest?
db2rest doesn't "need" a database to run itself, correct?
but if db2rest is to be useful it needs a db setup for a connection in order to serve as a gateway and provide API services, correct?

From this question, I think it would be great to document the actual requirements for db2rest to run.
I "think" the only requirements are:
1. 2 GB RAM
2. Java 17 or greater
3. anything else?

So opening issue #283
