### ISSUE TITLE
Schema should be optional

### ISSUE THREAD

**Issue by simasch** [kdhrubo/db2rest#80]
The schema should be optional and derived from the database.
For example are those the defaults:

- PostgreSQL -> public
- Oracle -> <the user name of the logged in user>

**Comment by kdhrubo** [comment]
DB_SCHEMAS - is a restriction list of schemas. May be better to rename it. 

Are you suggesting - that the list of schemas is created at startup from JDBC Metadata?

**Comment by simasch** [comment]
No I'm suggesting that when there is no schema set the default schema of the database should be used.

PG -> public
ORA ->  The name of the user

**Comment by kdhrubo** [comment]
This is possible. 
What if the user has access to multiple schemas including the default ones. Should we consider all of them?

**Comment by thadguidry** [comment]
@kdhrubo I think, YES, since we should not be the ones dictating what schema (and hence which tables) are allowed access per user.  I feel that the Schema restriction is not a good concept to introduce into db2rest.  Those restrictions are all managed by the database already by user/role.  We should just default to what the user/role has access to.

Schema's in database terms are now (since ~2005) just containers for objects.  Those objects can be tables, stored procedures, etc.  Ownership is granted to an entire Schema (the set of objects), or granted to individual objects (or revoked/denied).  As a matter of fact, in some cases in some databases, a user can use a database without even having a database account (database principal) in many situations through implicit schema and user creation methods.

Generally, I don't see the need to get into the user management or access control policies, since those are handled by databases already?

**Comment by kdhrubo** [comment]
Makes total sense.

What happens if the user has access to two schemas that have two tables with same name.?

**Comment by thadguidry** [comment]
No idea.  What do you WANT to happen, depends on the query.
Example query asking for data from 2 tables with same identifier (table name) but different schema (technically under the covers of the database, they are NOT the same identifier, but only the same label of the table)
```sql
select * from schema1.tableA
union all
select * from schema2.tableB
```

**Comment by kdhrubo** [comment]
The query needs to apply to 1 schema only. 
There is support for multi-tenancy pattern - schema per tenant. In this mode, each tenant will have a schema. 
That would mean 1000 union queries and of course data leaks. In other words, schema per tenant pattern would not work. 

Hence proposing the following:

1. Let the DB user have access to n of schemas (which is required for schema per tenant).
2. It will be mandatory to mention the schema name as a request parameter instead of a header.
3. Query only the table in the specified schema (db user has access to this schema)

This model looks good for the microservice model of deployment where each service tend to own its data in a schema/db.

**Comment by simasch** [comment]
One user can have multiple schemes also in a microservices architecture.

This means a join can be of two tables from different schemes

**Comment by kdhrubo** [comment]
For the initial releases will keep this as a limitation. Will revisit this issue later. Keeping it open.

**Comment by kdhrubo** [comment]
#195 - optional schema for delete.

**Comment by kdhrubo** [comment]
#217 - optional schema for insert

**Comment by kdhrubo** [comment]
#296 - optional schema for update. 

So now everything is cleared of schema dependency.
